{
 "title": "Crypto Sentiment vs Price Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "asset", "label": "Asset", "query": "BTC,ETH" }
  ]
 },
 "panels": [
  {
   "title": "Fear vs Return Hourly",
   "type": "xychart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "gold_db",
     "rawSql": "SELECT\n  s.fear_index   AS fear,\n  p.price_return AS return\nFROM mv_sentiment_5m s\nJOIN mv_price_return_5m p\n  ON s.window_start = p.window_start\n AND s.asset = p.asset\nWHERE s.asset = '$asset'\n"
    }
   ]
  },
  {
   "title": "Fear Index Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT window_start AS time, asset, fear_index FROM mv_sentiment_5m WHERE $__timeFilter(window_start) ORDER BY time asc, asset"
    }
   ]
  },
  {
   "title": "Price Return",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT window_start AS time, asset, price_return FROM mv_price_return_5m WHERE $__timeFilter(window_start)  ORDER BY time asc, asset"
    }
   ]
  },
  {
   "title": "Sentiment Composition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT window_start AS time, fear_index, joy, anger, sadness FROM mv_sentiment_5m WHERE asset = '$asset' AND $__timeFilter(window_start)  ORDER BY time asc, asset"
    }
   ]
  }
 ]
}